runtime: python39
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  # Add any environment variables required by your application
  VARIABLE_NAME: "value"

handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto
